#!/usr/bin/make
#
# Closest Pair Lab						February 23, 2023
#
# source: Makefile
# author: @misael-diaz
#
# Synopsis:
# Defines the Makefile for building the program with GNU make.
#
# Copyright (c) 2023 Misael Diaz-Maldonado
# This file is released under the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#

all: prng

prng: test-prng
	@$(MAKE) -C test-prng

clean:
	@$(MAKE) -C test-prng clean
